export const CHUNK_SIZE = 100 * 100;
export const SPAWN_PLANTS_PER_CHUNK = 0.2;
export const SPAWN_HERBIVORES_PER_CHUNK = 0.2;
export const SPAWN_CARNIVORES_PER_CHUNK = 0.05;

export const FACTOR_PHYSIC_ELEMENT_WEIGHT = 1;

export const FACTOR_ANIMAL_MAX_BITE = 0.6;
export const FACTOR_ANIMAL_VISIBILITY = 50;
export const FACTOR_ANIMAL_VELOCITY = 1;
export const FACTOR_ANIMAL_VELOCITY_HUNTING = 100;
export const FACTOR_ANIMAL_VELOCITY_ESCAPING = 200;
export const FACTOR_ANIMAL_MAX_VELOCITY = 7;
export const FACTOR_ANIMAL_FRICTION = 0.01;
export const FACTOR_ANIMAL_CONSUMPTION = 0.1;

export const FACTOR_CELL_MAX_SIZE = 15;
export const FACTOR_CELL_MITOSIS_SPLIT_VELOCITY = 5;
export const FACTOR_CELL_MITOSIS_GROWTH = 1.8;
export const FACTOR_CELL_MITOSIS_MAX_SIZE = 13;

export const FACTOR_PLANT_WEIGHT = 1;
export const FACTOR_PLANT_MAX_AREA = 100;
export const FACTOR_PLANT_GROWTH = 0.05;

export const FACTOR_CARNIVORE_VELOCITY = 2;
export const FACTOR_CARNIVORE_VELOCITY_HUNTING = 100;
export const FACTOR_CARNIVORE_MAX_VELOCITY = 6 + Math.random();
export const FACTOR_CARNIVORE_CONSUMPTION = 0.01;

export const MAP_DEFAULT_WIDTH = 100;
export const MAP_DEFAULT_HEIGHT = 100;
export const MAP_DEFAULT_CELL_SIZE = 10;
