name: Deploy to Github Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run test-with-coverage
      - run: bun run build
      - run: cp -r ./coverage dist/coverage

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy coverage
        uses: codecov/codecov-action@v4
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./coverage/clover.xml # optional
          name: lulas # optional
